### ISSUE TITLE
inview_notifier_list 1.0.0 depends on stream_transform ^1.1.0, while camera depends on stream_transform ^2.0.0,

### ISSUE THREAD

**Issue by threepat1** [rvamsikrishna/inview_notifier_list#30]
can you please update stream_transform?

**Comment by Ebrahimhammad** [comment]
I am getting the same thing with another plugin

Because inview_notifier_list >=0.0.4 depends on stream_transform ^1.1.0 and google_maps_flutter_platform_interface >=2.0.0 depends on stream_transform ^2.0.0, inview_notifier_list >=0.0.4 is incompatible with google_maps_flutter_platform_interface >=2.0.0.
And because google_maps_flutter 2.0.6 depends on google_maps_flutter_platform_interface ^2.0.0 and no versions of google_maps_flutter match >2.0.6 <3.0.0, inview_notifier_list >=0.0.4 is incompatible with google_maps_flutter ^2.0.6.

**Comment by SedlarDavid** [comment]
> I am getting the same thing with another plugin
> 
> Because inview_notifier_list >=0.0.4 depends on stream_transform ^1.1.0 and google_maps_flutter_platform_interface >=2.0.0 depends on stream_transform ^2.0.0, inview_notifier_list >=0.0.4 is incompatible with google_maps_flutter_platform_interface >=2.0.0.
> And because google_maps_flutter 2.0.6 depends on google_maps_flutter_platform_interface ^2.0.0 and no versions of google_maps_flutter match >2.0.6 <3.0.0, inview_notifier_list >=0.0.4 is incompatible with google_maps_flutter ^2.0.6.

That said, older versions of inview_notifier_list has dependency on stream_transform ^1.1.0 which is old now.
You can use my fork of inview_notifier_list where this dependency is updated and this issue is resolved. I will work on my PR hopefully next week to make it ready for full MR.

**Comment by CosmicPangolin** [comment]
@rvamsikrishna

The stream_transform dependency version is conflicting with many libraries in the pub ecosystem - cameras, build_runner, etc.  Can you please bump this dependency...??

**Comment by rvamsikrishna** [comment]
@CosmicPangolin the package has been updated to use the latest dependencies and null safety
